Add PR stats to open/closed pull request comment
Teamwork/github-sync pull request #31
Opened 2020-10-30 16:43 UTC by toffentoffen

- Created new function to extract stats from pr.
- Enhanced open and close pr comments with those stats.

Fixes #27

2020-10-31 08:42 UTC, miguelbemartin requested changes
There is an error when executing the pipeline:

`| /src/teamwork.sh: line 47: pr_stats_array[1]: unbound variable`

2020-11-04 16:00 UTC, toffentoffen commented
Finally was able to run the test after upgrading my docker for mac:
````
act pull_request -e tests/events/pull_request_opened.json
[teamwork/Ensure this project runs] 🚀  Start image=node:12.6-buster-slim
[teamwork/Ensure this project runs]   🐳  docker run image=node:12.6-buster-slim entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[teamwork/Ensure this project runs]   🐳  docker cp src=/Users/marcnavarro/teamwork/github-sync/. dst=/github/workspace
[teamwork/Ensure this project runs] ⭐  Run actions/checkout@v1
[teamwork/Ensure this project runs]   ✅  Success - actions/checkout@v1
[teamwork/Ensure this project runs] ⭐  Run ./
[teamwork/Ensure this project runs]   🐳  docker build -t act-github-sync:latest /Users/marcnavarro/teamwork/github-sync
[teamwork/Ensure this project runs]   🐳  docker run image=act-github-sync:latest entrypoint=[] cmd=["" "localhost" "test_api_token"]
| --------------
| Running the process...
| --------------
| Event: pull_request - Action: opened
| --------------
| Task found with the id: 123
| --------------
| Test - Simulate request. Task ID: 123 - Comment:
|   **username** opened a PR: **This is an example of a title for the PR.**
|   [https://github.com/teamwork/github-sync/pull/1](https://github.com/teamwork/github-sync/pull/1)
|   ---
|   Stats: 1 commits, 4 files changed, +2, -3
|
| --------------
| Task found with the id: 456
| --------------
| Test - Simulate request. Task ID: 456 - Comment:
|   **username** opened a PR: **This is an example of a title for the PR.**
|   [https://github.com/teamwork/github-sync/pull/1](https://github.com/teamwork/github-sync/pull/1)
|   ---
|   Stats: 1 commits, 4 files changed, +2, -3
|
[teamwork/Ensure this project runs]   ✅  Success - ./
````

2020-11-08 16:52 UTC, miguelbemartin commented
@toffentoffen updated some minor style for the comments and it is ready to be merged. 

Thanks for the effort working on this one :)

2020-11-08 16:53 UTC, miguelbemartin approved these changes

2020-11-08 16:53 UTC, merged